# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-14 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='huluwa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名字')),
                ('atrribute', models.CharField(max_length=30, verbose_name='属性')),
                ('birthday', models.DateField(auto_now_add=True, verbose_name='出生日期')),
                ('height', models.IntegerField(default=170, verbose_name='身高')),
                ('skill', models.CharField(max_length=400, verbose_name='技能')),
            ],
            options={
                'db_table': 'calabash_boy',
            },
        ),
    ]
